# Generated by Django 6.0.2 on 2026-03-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("description", models.TextField(max_length=200)),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                ("picture", models.ImageField(upload_to="recipes/")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "foodCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flavourindexApp.foodcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "recipes",
                "ordering": ["title"],
            },
        ),
    ]
