# Generated by Django 6.0.2 on 2026-03-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flavourindexApp", "0005_seed_food_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
    ]
