# Generated by Django 5.2.12 on 2026-03-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavourindexApp', '0006_alter_foodcategory_id_alter_recipe_id_and_more'),
        ('flavourindexApp', '0006_alter_recipe_picture'),
    ]

    operations = [
    ]
